name = "Cave Story"
home = "https://discord.com/channels/731205301247803413/1083474864150695956"
default_url = "https://github.com/kl3cks7r/Archipelago/releases/download/v{{version}}/cave_story.apworld"

[versions]
"0.4.1" = {}
"0.5.0" = { url = "https://github.com/kl3cks7r/Archipelago/releases/download/v0.5/cave_story.apworld" }
