name = "Diddy Kong Racing"
home = "https://discord.com/channels/731205301247803413/1057754627795337387"
default_url = "https://github.com/zakwiz/DiddyKongRacingAP/releases/download/v{{version}}/diddy_kong_racing.apworld"

[versions]
"0.3.1" = {}
"0.5.2" = {}
