name = "Final Fantasy 12 Open World"
home = "https://discord.com/channels/731205301247803413/1229091295465570456"
default_url = "https://github.com/Bartz24/Archipelago/releases/download/{{version}}/ff12_open_world.apworld"

[versions]
"0.4.2" = {}
"0.5.1" = {}
