name = "Manual_FFXIV_Silasary"
display_name = "Manual: Final Fantasy XIV"
home = "https://discord.com/channels/1097532591650910289/1187584337877684294"
default_url = "https://github.com/silasary/APxiv/releases/download/{{version}}/ffxiv.apworld"

[versions]
"0.19.2" = {}
"0.21.0" = {}
"0.21.1" = {}
"0.21.2" = {}
"0.22.0" = {}
